name: Test ssh command
on: push

env:
  FIRST_NAME: Terry
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: tarunjangra/ssh-remote-cmd@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME"
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"